services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    # image: hashicorp/terraform:1.9
    container_name: cloudflare_manager
    working_dir: /workspace
    volumes:
      - ./terraform:/workspace
      - ./scripts:/scripts

    env_file:
      - .env

    entrypoint: [
        "/bin/sh",
        "-c",
        "rm /workspace/logs.txt && \
        touch /workspace/logs.txt && \
        chmod +x /scripts/docker.sh && \
        /scripts/docker.sh | tee -ai /workspace/logs.txt && \
        while true; do sleep 1000; done"
    ]

    stdin_open: true
    tty: true
    restart: unless-stopped

